"""SuperAdmin SaaS

Revision ID: 6a788395fddb
Revises: eddfa65f7733
Create Date: 2026-03-07 00:38:17.382963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a788395fddb'
down_revision: Union[str, Sequence[str], None] = 'eddfa65f7733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes_suscripcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('limite_edificios', sa.Integer(), nullable=True),
    sa.Column('precio_mensual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_planes_suscripcion_id'), 'planes_suscripcion', ['id'], unique=False)
    op.create_table('tipos_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipos_pago_id'), 'tipos_pago', ['id'], unique=False)
    op.add_column('empresas', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.add_column('empresas', sa.Column('estado_suscripcion', sa.String(), nullable=True))
    op.add_column('empresas', sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'empresas', 'planes_suscripcion', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empresas', type_='foreignkey')
    op.drop_column('empresas', 'fecha_vencimiento')
    op.drop_column('empresas', 'estado_suscripcion')
    op.drop_column('empresas', 'plan_id')
    op.drop_index(op.f('ix_tipos_pago_id'), table_name='tipos_pago')
    op.drop_table('tipos_pago')
    op.drop_index(op.f('ix_planes_suscripcion_id'), table_name='planes_suscripcion')
    op.drop_table('planes_suscripcion')
    # ### end Alembic commands ###
