"""Add concepto to pagos

Revision ID: 84b0076628c0
Revises: 19b0ee23a9d9
Create Date: 2026-03-04 02:14:40.874821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b0076628c0'
down_revision: Union[str, Sequence[str], None] = '19b0ee23a9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagos', sa.Column('concepto', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagos', 'concepto')
    # ### end Alembic commands ###
