"""initial_postgres

Revision ID: d9fd8e868213
Revises: 
Create Date: 2026-03-02 23:30:52.029605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9fd8e868213'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edificios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edificios_id'), 'edificios', ['id'], unique=False)
    op.create_index(op.f('ix_edificios_nombre'), 'edificios', ['nombre'], unique=False)
    op.create_table('inquilinos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellidos', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('datos_aval', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquilinos_correo'), 'inquilinos', ['correo'], unique=True)
    op.create_index(op.f('ix_inquilinos_id'), 'inquilinos', ['id'], unique=False)
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edificio_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('renta_mensual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('inventario', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['edificio_id'], ['edificios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departamentos_id'), 'departamentos', ['id'], unique=False)
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('monto_deposito', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_id'), 'contratos', ['id'], unique=False)
    op.create_table('tickets_mantenimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('costo_reparacion', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_mantenimiento_id'), 'tickets_mantenimiento', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('fecha_correspondiente', sa.DateTime(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recargos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('recibo_pdf_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_tickets_mantenimiento_id'), table_name='tickets_mantenimiento')
    op.drop_table('tickets_mantenimiento')
    op.drop_index(op.f('ix_contratos_id'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_departamentos_id'), table_name='departamentos')
    op.drop_table('departamentos')
    op.drop_index(op.f('ix_inquilinos_id'), table_name='inquilinos')
    op.drop_index(op.f('ix_inquilinos_correo'), table_name='inquilinos')
    op.drop_table('inquilinos')
    op.drop_index(op.f('ix_edificios_nombre'), table_name='edificios')
    op.drop_index(op.f('ix_edificios_id'), table_name='edificios')
    op.drop_table('edificios')
    # ### end Alembic commands ###
