"""add_motivo_terminacion_to_contratos

Revision ID: eddfa65f7733
Revises: 2b3e8d85b4b4
Create Date: 2026-03-05 22:00:47.037225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eddfa65f7733'
down_revision: Union[str, Sequence[str], None] = '2b3e8d85b4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos', sa.Column('motivo_terminacion', sa.String(), nullable=True))
    op.add_column('contratos', sa.Column('fecha_terminacion', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contratos', 'fecha_terminacion')
    op.drop_column('contratos', 'motivo_terminacion')
    # ### end Alembic commands ###
